name: "Pratik's Blogs"
description: "Programming essays, thoughts, and notes."
baseurl: "" # Set to empty for root user domain (https://pratikdate.github.io)
url: "https://pratikdate.github.io"

collections:
  blogs:
    output: true
    permalink: /blog/:name/

defaults:
  - scope:
      path: ""
      type: "blogs"
    values:
      layout: "blog"
